const questions = {
  1: { text: "Which is the oldest name of the Harappan Civilization?", options: ["Indus Civilization", "Saraswati Civilization", "Aryan Civilization", "Dravidian Civilization"], correct: "1", image: '' },
2: { text: "According to archaeological tradition, which name is most appropriate for the Indus Civilization?", options: ["Indus Civilization", "Harappan Civilization", "Saraswati Civilization", "Sindhu Civilization"], correct: "2", image: '' },
3: { text: "According to geographical point of view, which name is most suitable for the Indus Civilization?", options: ["Indus Civilization", "Harappan Civilization", "Indus–Saraswati Civilization", "Indo-Gangetic Civilization"], correct: "3", image: '' },
4: { text: "What is the most accepted period of the Harappan Civilization?", options: ["3000 BC–2000 BC", "2600 BC–1900 BC", "2500 BC–1750 BC", "2000 BC–1500 BC"], correct: "3", image: '' },
5: { text: "Who was the first scholar to use the term 'Indus Civilization'?", options: ["Mortimer Wheeler", "John Marshall", "Alexander Cunningham", "Rakhaldas Banerjee"], correct: "2", image: '' },
6: { text: "The Indus Civilization belongs to which period?", options: ["Palaeolithic Age", "Mesolithic Age", "Neolithic Age", "Chalcolithic/Bronze Age"], correct: "4", image: '' },
7: { text: "The Indus Civilization was spread over which of the following regions?", options: ["Only Punjab and Sindh", "Sindh, Baluchistan, Punjab, Haryana, Rajasthan, Gujarat, Western U.P., Northern Maharashtra", "Only Gujarat and Rajasthan", "Only Punjab and Gujarat"], correct: "2", image: '' },
8: { text: "Which region is considered the heartland of the Indus Civilization?", options: ["Rajasthan–Gujarat Axis", "Harappa–Ghaggar–Mohenjodaro Axis", "Sindh–Punjab Axis", "Lothal–Kalibangan Axis"], correct: "2", image: '' },
9: { text: "Which is the northern-most site of the Indus Civilization?", options: ["Ropar (Sutlej)/Punjab", "Kalibangan (Ghaggar)/Rajasthan", "Lothal (Sabarmati)/Gujarat", "Alamgirpur (Hindon)/U.P."], correct: "1", image: '' },
10: { text: "Which is currently considered the northern-most site of the Indus Civilization?", options: ["Ropar (Sutlej)/Punjab", "Manda (Chenab)/Jammu & Kashmir", "Kalibangan (Ghaggar)/Rajasthan", "Harappa (Ravi)/Pakistan"], correct: "2", image: '' },
11: { text: "Which is the southern-most site of the Indus Civilization now known?", options: ["Bhagatrav (Kim)/Gujarat", "Daimabad (Pravara)/Maharashtra", "Lothal (Sabarmati)/Gujarat", "Sutkagendor (Makran Coast)"], correct: "2", image: '' },
12: { text: "Which is the eastern-most site of the Indus Civilization?", options: ["Kalibangan", "Rangpur", "Alamgirpur (Hindon)/U.P.", "Sutkagendor"], correct: "3", image: '' },
13: { text: "Which is the western-most site of the Indus Civilization?", options: ["Sutkagendor (Makran Coast)", "Lothal", "Ropar", "Kalibangan"], correct: "1", image: '' },
14: { text: "Which were the capital cities of the Indus Civilization?", options: ["Lothal and Kalibangan", "Harappa and Mohenjodaro", "Dholavira and Lothal", "Rangpur and Ropar"], correct: "2", image: '' },
15: { text: "Which of the following were the port cities of the Indus Civilization?", options: ["Harappa, Mohenjodaro, Kalibangan", "Lothal, Sutkagendor, Allahdino, Balakot, Kuntasi", "Ropar, Daimabad, Alamgirpur", "Banawali, Dholavira, Rangpur"], correct: "2", image: '' },
  16: { text: "Which river was associated with the Harappa site?", options: ["Indus", "Ravi", "Ghaggar", "Bhogava"], correct: "2", image: '' },
17: { text: "In which district is Harappa located?", options: ["Larkana", "Sahiwal", "Fatehabad", "Kutch"], correct: "2", image: '' },
18: { text: "Who excavated the Harappa site in 1921?", options: ["Rakhal Das Banerji", "Daya Ram Sahni", "S.R. Rao", "R.S. Bist"], correct: "2", image: '' },
19: { text: "Which river flows near Mohenjodaro?", options: ["Ravi", "Ghaggar", "Indus", "Bhogava"], correct: "3", image: '' },
20: { text: "In which province is Mohenjodaro located?", options: ["Sindh", "Punjab", "Baluchistan", "Gujarat"], correct: "1", image: '' },
21: { text: "Who excavated Mohenjodaro in 1922?", options: ["Daya Ram Sahni", "Rakhal Das Banerji", "J.P. Joshi", "B.V. Lal"], correct: "2", image: '' },
22: { text: "Which site is known as the 'Oasis of Sindh'?", options: ["Harappa", "Lothal", "Mohenjodaro", "Chanhudaro"], correct: "3", image: '' },
23: { text: "Chanhudaro is situated on which river?", options: ["Indus", "Ravi", "Ghaggar", "Bhogava"], correct: "1", image: '' },
24: { text: "Who excavated Chanhudaro in 1925?", options: ["Mackay", "S.R. Rao", "Daya Ram Sahni", "Amalanand Ghosh"], correct: "1", image: '' },
25: { text: "Lothal was situated on which river?", options: ["Luni", "Ghaggar", "Bhogava", "Indus"], correct: "3", image: '' },
26: { text: "Who excavated the Lothal site?", options: ["S.R. Rao", "Mackay", "J.P. Joshi", "R.S. Bist"], correct: "1", image: '' },
27: { text: "Kalibangan means what in English?", options: ["City of gold", "Oasis of Sindh", "Bangles of black colour", "Land of fire"], correct: "3", image: '' },
28: { text: "Which river flows near Kalibangan?", options: ["Indus", "Ghaggar", "Ravi", "Bhogava"], correct: "2", image: '' },
29: { text: "Who excavated Kalibangan in 1951?", options: ["Daya Ram Sahni", "Amalanand Ghosh", "S.R. Rao", "B.V. Lal"], correct: "2", image: '' },
30: { text: "Banawali is located on the banks of which river?", options: ["Ravi", "Ghaggar", "Luni", "Bhogava"], correct: "2", image: '' },
31: { text: "Who excavated Banawali?", options: ["R.S. Bist", "J.P. Joshi", "B.V. Lal", "Mackay"], correct: "1", image: '' },
32: { text: "Which river was associated with Dholavira?", options: ["Luni", "Ghaggar", "Ravi", "Indus"], correct: "1", image: '' },
33: { text: "In which district is Dholavira located?", options: ["Ahmedabad", "Kutch", "Fatehabad", "Sahiwal"], correct: "2", image: '' },
34: { text: "Who excavated Dholavira in 1967–68?", options: ["J.P. Joshi", "S.R. Rao", "Mackay", "R.S. Bist"], correct: "1", image: '' },
35: { text: "From which places did the Harappans import gold?", options: ["Kolar, Afghanistan, Persia (Iran)", "South India only", "Egypt and Arabia", "Mesopotamia only"], correct: "1", image: '' },
36: { text: "Which region supplied silver to the Indus Civilization?", options: ["South India and Persia", "Afghanistan, Persia, and South India", "Arabia and Kolar", "Mesopotamia and Egypt"], correct: "2", image: '' },
37: { text: "Copper was imported by the Indus people mainly from which places?", options: ["Khetri, Baluchistan, Arabia", "Kolar, Persia, Afghanistan", "Rajasthan only", "Iran and Egypt"], correct: "1", image: '' },
38: { text: "From which region did the Harappans get Lapis Lazuli and Sapphire?", options: ["Central Asia", "Badak-shan (Afghanistan)", "Persia (Iran)", "Arabia"], correct: "2", image: '' },
39: { text: "From where was Jade imported by the Indus people?", options: ["Central Asia", "Persia", "Afghanistan", "India"], correct: "1", image: '' },
40: { text: "Which region supplied Steatite to the Indus Civilization?", options: ["Kirthar Hills (Pakistan) and Shaheir-i-Sokhta (Iran)", "Badak-shan and Baluchistan", "Khetri and Kolar", "Saurashtra and West India"], correct: "1", image: '' },
41: { text: "From where was Amethyst obtained?", options: ["Afghanistan", "Maharashtra", "Saurashtra", "Baluchistan"], correct: "2", image: '' },
42: { text: "Agate, Chalcedony, and Carnelian were imported from which region?", options: ["Saurashtra and West India", "Kolar and Karnataka", "Persia and Afghanistan", "Rajasthan and U.P."], correct: "1", image: '' },
43: { text: "Which of the following items were exported by the Harappans?", options: ["Iron tools and weapons", "Agricultural products, cotton goods, terracotta figurines, pottery", "Bronze idols and coins", "Gold and silver ornaments only"], correct: "2", image: '' },
44: { text: "Which site is known for exporting beads during the Harappan period?", options: ["Harappa", "Chanhudaro", "Mohenjodaro", "Kalibangan"], correct: "2", image: '' },
45: { text: "Conch-shell products were mainly exported from which Harappan site?", options: ["Lothal", "Ropar", "Banawali", "Dholavira"], correct: "1", image: '' },
46: { text: "Which metal was unknown to the people of the Indus Civilization?", options: ["Copper", "Bronze", "Iron", "Tin"], correct: "3", image: '' },
47: { text: "The Sumerian texts refer to trade relations with which region known as 'Meluhha'?", options: ["Egypt", "Indus region", "China", "Arabia"], correct: "2", image: '' },
48: { text: "Which two Indus sites were found in Afghanistan?", options: ["Harappa and Mohenjodaro", "Shatughai and Mundigag", "Kalibangan and Lothal", "Banawali and Ropar"], correct: "2", image: '' },
49: { text: "According to Sumerian texts, which two places served as intermediate trade stations between Mesopotamia and the Indus region?", options: ["Dilmun (Bahrain) and Makan (Makran Coast)", "Ur and Kish", "Susa and Lagash", "Egypt and Oman"], correct: "1", image: '' },
50: { text: "At which Mesopotamian sites were Harappan seals discovered?", options: ["Susa and Ur", "Dilmun and Makan", "Eridu and Kish", "Babylon and Nineveh"], correct: "1", image: '' },
51: { text: "The Harappans were the earliest people to produce which textile?", options: ["Silk", "Cotton", "Linen", "Wool"], correct: "2", image: '' },
52: { text: "What name did the Greeks give to Indian cotton?", options: ["Meluhha", "Sindon", "Indikon", "Makran"], correct: "2", image: '' },
53: { text: "In the absence of coins, what was the mode of exchange in the Indus Civilization?", options: ["Use of silver pieces", "Credit system", "Barter system", "Use of seals as currency"], correct: "3", image: '' },
54: { text: "Which Harappan site served as an ancient port?", options: ["Harappa", "Lothal", "Kalibangan", "Mohenjodaro"], correct: "2", image: '' },
55: { text: "What was the primary character of the Indus Civilization?", options: ["Rural", "Urban", "Nomadic", "Tribal"], correct: "2", image: '' },
56: { text: "What is believed to be the ruling authority of the Indus Civilization?", options: ["Priests", "Kings", "Merchants", "Military chiefs"], correct: "3", image: '' },
57: { text: "Did the Harappans build temples for worship?", options: ["Yes, many temples found", "No, no temple has been unearthed", "Only one temple at Lothal", "Yes, at Harappa only"], correct: "2", image: '' },
58: { text: "Which figurine is most commonly found in Harappan sites?", options: ["King statue", "Mother-Goddess", "Priest statue", "Bull figurine"], correct: "2", image: '' },
59: { text: "What does the worship of Yoni in Harappan culture indicate?", options: ["Animal worship", "Female fertility worship", "Sun worship", "Ancestor worship"], correct: "2", image: '' },
60: { text: "Who was the chief male deity of the Harappans?", options: ["Vishnu", "Agni", "Pasupati Mahadeva (Proto-Shiva)", "Indra"], correct: "3", image: '' },
61: { text: "How is Pasupati Mahadeva represented in Harappan seals?", options: ["Sitting in yogic posture surrounded by animals", "Standing with bow and arrow", "On a throne with attendants", "Worshipping the sun"], correct: "1", image: '' },
62: { text: "Which animals surround Pasupati Mahadeva in Harappan seals?", options: ["Elephant, tiger, rhino, buffalo", "Lion, cow, goat, horse", "Deer, bull, ox, peacock", "Horse, camel, goat, buffalo"], correct: "1", image: '' },
63: { text: "Which two animals appear at the feet of Pasupati Mahadeva?", options: ["Deer", "Goat", "Oxen", "Dogs"], correct: "1", image: '' },
64: { text: "Which form of worship was practiced by the Harappans indicating early Shiva-Shakti tradition?", options: ["Sun and Moon worship", "Phallic (Lingam) and Yoni worship", "Ancestor worship", "Fire worship"], correct: "2", image: '' },
65: { text: "Which animal was particularly sacred to the Harappans and linked to Shiva worship?", options: ["Elephant", "Humped bull", "Tiger", "Horse"], correct: "2", image: '' },
66: { text: "What type of worships were prevalent among Harappans as shown by seals and excavations?", options: ["Animal and tree worship", "Sun and fire worship", "Ancestor and spirit worship", "Moon and water worship"], correct: "1", image: '' },
67: { text: "Which tree was especially revered by the Harappans?", options: ["Peepal", "Banyan", "Neem", "Mango"], correct: "1", image: '' },
61: { text: "What type of script was used by the Harappans?", options: ["Alphabetical script", "Pictographic script", "Hieroglyphic script", "Syllabic script"], correct: "2", image: '' },
62: { text: "The Harappan script was mainly found on which objects?", options: ["Pottery", "Rocks", "Seals", "Copper plates"], correct: "3", image: '' },
63: { text: "The writing style of the Harappan script was:", options: ["Right to left only", "Left to right only", "Boustrophedon", "Circular"], correct: "3", image: '' },
64: { text: "Which site provided evidence that Harappan writing was boustrophedon?", options: ["Harappa", "Mohenjodaro", "Kalibanga", "Lothal"], correct: "3", image: '' },
65: { text: "The Harappan script has been referred to as:", options: ["Proto-Aryan", "Proto-Dravidian", "Proto-Indo-European", "Proto-Sanskrit"], correct: "2", image: '' },
66: { text: "Which is the oldest script of the Indian subcontinent?", options: ["Brahmi", "Kharosthi", "Harappan", "Devanagari"], correct: "3", image: '' },
  67: { text: "Which is the oldest deciphered script in India?", options: ["Harappan", "Kharosthi", "Brahmi", "Tamil"], correct: "3", image: '' },
68: { text: "Most of the later Indian scripts developed from which ancient script?", options: ["Harappan", "Brahmi", "Kharosthi", "Devanagari"], correct: "2", image: '' },
69: { text: "Which material was mainly used in the manufacture of Harappan seals?", options: ["Terracotta", "Copper", "Steatite", "Bronze"], correct: "3", image: '' },
70: { text: "Which animal is most commonly represented in Indus seals?", options: ["Humped bull", "Humpless bull", "Elephant", "Unicorn"], correct: "2", image: '' },
71: { text: "What was the most common method of disposal of the dead in Harappan Civilization?", options: ["Cremation", "Exposure to birds", "Inhumation or complete burial", "Water burial"], correct: "3", image: '' },
  72: { text: "The origin of which symbol can be traced to the Indus Civilization?", options: ["Om", "Lotus", "Swastika", "Trishul"], correct: "3", image: '' },
73: { text: "Who accused Indra of causing the decline of the Indus Civilization?", options: ["Daya Ram Sahni", "M. Wheeler", "S.R. Rao", "Rakhal Das Bannerji"], correct: "2", image: '' },
74: { text: "According to Rigveda, the battle at 'Hariyumpia' has been identified with which site?", options: ["Kalibanga", "Lothal", "Harappa", "Dholavira"], correct: "3", image: '' },
75: { text: "The makers of the Indus Valley Civilization were mostly believed to be:", options: ["Aryans", "Dravidians", "Persians", "Sumerians"], correct: "2", image: '' },
76: { text: "Which of the following civilizations were contemporary to the Indus Civilization?", options: ["Greek, Roman, Chinese", "Mesopotamia, Egypt, China", "Babylonian, Greek, Egyptian", "Mayan, Egyptian, Roman"], correct: "2", image: '' },
  
  
  
};

const explanations = {
  1: { text: "The oldest name of the Harappan Civilization is 'Indus Civilization', as it was discovered along the Indus River valley.", image: "" },
2: { text: "Archaeologists call it the Harappan Civilization because Harappa was the first site discovered in 1921 by Rakhaldas Banerjee.", image: "" },
3: { text: "Geographically, the term 'Indus–Saraswati Civilization' is preferred since around 80% of settlements were along the Saraswati river.", image: "" },
4: { text: "The most accepted period of the Harappan Civilization is 2500 BC–1750 BC, determined by Carbon-14 dating.", image: "" },
5: { text: "John Marshall, the Director-General of ASI, first used the term 'Indus Civilization' to describe the discoveries at Harappa and Mohenjodaro.", image: "" },
6: { text: "The Indus Civilization belongs to the Proto-Historic or Chalcolithic/Bronze Age period, known for the use of copper and bronze tools.", image: "" },
7: { text: "The civilization extended across modern-day Pakistan and northwest India, including Sindh, Baluchistan, Punjab, Haryana, Rajasthan, Gujarat, Western U.P., and Northern Maharashtra.", image: "" },
8: { text: "The Harappa–Ghaggar–Mohenjodaro axis is regarded as the heartland of the Indus Civilization where maximum settlements were concentrated.", image: "" },
9: { text: "Ropar (on the Sutlej in Punjab) was earlier considered the northern-most site of the Indus Civilization.", image: "" },
10: { text: "Manda (on the Chenab in Jammu & Kashmir) is now recognized as the northern-most site of the Indus Civilization.", image: "" },
11: { text: "Daimabad (on the Pravara River in Maharashtra) is the southern-most site of the Indus Civilization, discovered later than Bhagatrav.", image: "" },
12: { text: "Alamgirpur (on the Hindon River in Uttar Pradesh) is the eastern-most site of the Indus Civilization.", image: "" },
13: { text: "Sutkagendor (on the Makran Coast at the Pakistan–Iran border) is the western-most site of the Indus Civilization.", image: "" },
14: { text: "Harappa and Mohenjodaro served as the main capital cities of the Indus Civilization, both major urban centers with advanced planning.", image: "" },
15: { text: "Lothal, Sutkagendor, Allahdino, Balakot, and Kuntasi were important port cities facilitating maritime trade in the Indus Civilization.", image: "" },
  
  16: { text: "Harappa was located on the banks of the Ravi River in Sahiwal district of Punjab (Pakistan).", image: "" },
17: { text: "Harappa is situated in Sahiwal district of Punjab province, Pakistan, and was one of the first sites discovered in 1921.", image: "" },
18: { text: "Harappa was excavated by Daya Ram Sahni in 1921, later by Madho Swaroop Vatsa (1926) and Wheeler (1946).", image: "" },
19: { text: "Mohenjodaro was situated on the banks of the Indus River in Larkana district of Sindh, Pakistan.", image: "" },
20: { text: "Mohenjodaro lies in Sindh province of Pakistan and was one of the most advanced urban centers of the Indus Civilization.", image: "" },
21: { text: "Rakhal Das Banerji discovered and excavated Mohenjodaro in 1922, followed by Mackay and Wheeler.", image: "" },
22: { text: "Mohenjodaro is known as the 'Nakhlistan' or 'Oasis of Sindh' due to its fertile and well-developed area.", image: "" },
23: { text: "Chanhudaro is located on the Indus River in Nawabshah district, Sindh, Pakistan.", image: "" },
24: { text: "Mackay excavated Chanhudaro in 1925, followed by N.G. Mazumdar in 1931.", image: "" },
25: { text: "Lothal was situated on the Bhogava River near Ahmedabad district in Gujarat, India.", image: "" },
26: { text: "S.R. Rao excavated Lothal in 1954, revealing an ancient dockyard, one of the earliest in the world.", image: "" },
27: { text: "Kalibangan means 'the bangles of black colour'; it lies on the Ghaggar River in Rajasthan.", image: "" },
28: { text: "Kalibangan is located on the banks of the Ghaggar River in Hanumangarh district, Rajasthan.", image: "" },
29: { text: "Kalibangan was excavated by Amalanand Ghosh in 1951 and later by B.V. Lal and B.K. Thapar in 1961.", image: "" },
30: { text: "Banawali is located on the Ghaggar River in Fatehabad district, Haryana.", image: "" },
31: { text: "R.S. Bist excavated Banawali in 1973, which revealed both pre-Harappan and mature Harappan phases.", image: "" },
32: { text: "Dholavira was situated on the Luni River in Kutch district, Gujarat.", image: "" },
33: { text: "Dholavira is located in Kutch district of Gujarat and is one of the largest Indus sites in India.", image: "" },
34: { text: "J.P. Joshi excavated Dholavira between 1967–68, revealing advanced urban planning and reservoirs.", image: "" },
35: { text: "The Harappans imported gold mainly from Kolar (Karnataka), Afghanistan, and Persia (Iran).", image: "" },
36: { text: "Silver was obtained from Afghanistan, Persia (Iran), and South India.", image: "" },
37: { text: "Copper sources for Harappans included Khetri (Rajasthan), Baluchistan, and Arabia.", image: "" },
38: { text: "Lapis Lazuli and Sapphire were imported from Badak-shan in Afghanistan.", image: "" },
39: { text: "Jade was imported from Central Asia and used for ornaments.", image: "" },
40: { text: "Steatite came from Shaheir-i-Sokhta in Iran and Kirthar Hills in Pakistan.", image: "" },
41: { text: "Amethyst was sourced from Maharashtra, India.", image: "" },
42: { text: "Agate, Chalcedony, and Carnelian stones came from Saurashtra and western India, used for beads and ornaments.", image: "" },

  43: { text: "Harappans exported agricultural produce, cotton textiles, terracotta figurines, pottery, beads (Chanhudaro), conch-shells (Lothal), ivory items, and copper goods.", image: "" },
44: { text: "Chanhudaro was famous for bead making and exported fine beads made of semi-precious stones.", image: "" },
45: { text: "Lothal, being a port city, exported conch-shell items and was an important trade hub.", image: "" },
46: { text: "Iron was unknown to the Harappan people; their tools were made from copper and bronze.", image: "" },
47: { text: "Sumerian records mention trade with 'Meluhha', identified with the Indus region.", image: "" },
48: { text: "Shatughai and Mundigag are Indus sites located in Afghanistan, showing northern trade extensions.", image: "" },
49: { text: "Sumerian texts mention Dilmun (Bahrain) and Makan (Makran Coast) as intermediate trade stations between Mesopotamia and Indus.", image: "" },
50: { text: "Harappan seals were found at Susa and Ur in Mesopotamia, proving contact between both civilizations.", image: "" },
51: { text: "The Harappans were the earliest people in the world to produce and use cotton fabric.", image: "" },
52: { text: "The Greeks called Indian cotton 'Sindon', derived from 'Sindhu', the Sanskrit word for Indus.", image: "" },
53: { text: "As no coins have been discovered, barter was the main system of trade among Harappans.", image: "" },
54: { text: "Lothal was an ancient port city of the Indus Civilization, used for maritime trade via the Gulf of Khambhat.", image: "" },
55: { text: "The Indus Civilization was primarily urban, with planned cities, drainage, and trade networks.", image: "" },
56: { text: "Evidence suggests that merchants formed the ruling class, managing trade and administration.", image: "" },
57: { text: "No temples have been found; Harappans worshipped through figurines and symbols rather than temples.", image: "" },
58: { text: "The Mother-Goddess figurine is the most common, symbolizing fertility and creation.", image: "" },
59: { text: "Yoni worship represented female fertility and creative power in Harappan religion.", image: "" },
60: { text: "The chief male deity was Pasupati Mahadeva (Proto-Shiva), the lord of animals, depicted on seals.", image: "" },
61: { text: "Pasupati is shown sitting in yogic posture surrounded by animals, symbolizing control over nature.", image: "" },
62: { text: "Four animals — elephant, tiger, rhinoceros, and buffalo — surround Pasupati Mahadeva in the seal imagery.", image: "" },
63: { text: "Two deer appear at the feet of Pasupati Mahadeva, completing the religious depiction.", image: "" },
64: { text: "Phallic (Lingam) and Yoni worship in Harappan culture reflect early Shiva-Shakti worship traditions.", image: "" },
65: { text: "The humped bull was sacred to Harappans and associated with Shiva or Nandi worship.", image: "" },
66: { text: "Excavations reveal that animal worship (zoolatry) and tree worship, especially peepal, were common religious practices.", image: "" },
67: { text: "The Peepal tree was considered sacred by the Harappans and often depicted on seals.", image: "" },
61: { text: "The Harappan script was pictographic, with signs representing pictures or symbols rather than letters. It remains undeciphered till now.", image: "" },
62: { text: "The script is mainly found on seals made of steatite, which were used for trade and administrative purposes.", image: "" },
63: { text: "Harappan writing was boustrophedon, meaning the direction of writing alternated between right-to-left and left-to-right in successive lines.", image: "" },
64: { text: "Overlapping letters on potsherds from Kalibanga show that the Harappan script was written boustrophedon.", image: "" },
65: { text: "Linguistic studies suggest that the Harappan script belonged to a Proto-Dravidian language family.", image: "" },
66: { text: "The oldest known script in the Indian subcontinent is the Harappan script, found on seals and artifacts from the Indus Valley Civilization.", image: "" },
  67: { text: "The Brahmi script, known from around the 5th century BCE, is the oldest deciphered script in India.", image: "" },
68: { text: "Most later Indian scripts, including Devanagari and Tamil-Brahmi, evolved from the ancient Brahmi script.", image: "" },
69: { text: "Steatite, a soft stone, was commonly used by Harappans to craft seals, which often contained inscriptions and animal motifs.", image: "" },
70: { text: "Humpless bull motifs frequently appear on Indus seals, symbolizing strength and fertility.", image: "" },
71: { text: "Inhumation or complete burial was the usual method of disposing of the dead in the Harappan Civilization, as found in cemetery excavations.", image: "" },
72: { text: "The Swastika symbol, a sacred and auspicious mark in later Indian culture, originated in the Indus Civilization.", image: "" },
  73: { text: "Archaeologist M. Wheeler suggested that Indra, the Vedic god of storms, was responsible for the destruction of the Indus Civilization.", image: "" },
74: { text: "Rigveda mentions a battle at 'Hariyumpia', believed to be the same as Harappa, linking early Vedic texts with Indus sites.", image: "" },
75: { text: "Most scholars agree that the Harappans were Dravidians based on linguistic and cultural evidence.", image: "" },
76: { text: "The Indus Civilization existed alongside other ancient civilizations such as Mesopotamia, Egypt, and China.", image: "" },
  
  
  
};
